# Generated by Django 5.1.6 on 2025-11-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_goods_id_alter_goods_goods_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited_referals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_farm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_code',
        ),
    ]
